export const FETCH_DAILY_TASKS_REQUEST = 'FETCH_DAILY_TASKS_REQUEST'
export const CREATE_DAILY_TASKS_REQUEST = 'CREATE_DAILY_TASKS_REQUEST'
export const UPDATE_DAILY_TASK_PROGREASS_REQUEST = 'UPDATE_DAILY_TASK_PROGREASS_REQUEST'
export const FETCH_DAILY_TASK_TRACKER_REQUEST = 'FETCH_DAILY_TASK_TRACKER'